#!/usr/bin/env python3
"""
Test script to simulate RagFlow's gen_meta_filter function.
This helps understand what metadata filter conditions are generated by the LLM.
"""
import requests
import json
import datetime

# OpenRouter API Configuration
OPENROUTER_API_KEY = "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"
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
MODEL = "anthropic/claude-haiku-4.5"

# Meta filter prompt template (from rag/prompts/meta_filter.md)
# Using triple-brace escaping for JSON examples
META_FILTER_PROMPT_TEMPLATE = """You are a metadata filtering condition generator. Analyze the user's question and available document metadata to output a JSON array of filter objects. Follow these rules:

1. **Metadata Structure**: 
   - Metadata is provided as JSON where keys are attribute names (e.g., "color"), and values are objects mapping attribute values to document IDs.

2. **Output Requirements**:
   - Always output a JSON dictionary with only 2 keys: 'conditions'(filter objects) and 'logic' between the conditions ('and' or 'or').
   - Each filter object in conditions must have:
        "key": (metadata attribute name),
        "value": (string value to compare),
        "op": (operator from allowed list)
   - Logic between all the conditions: 'and'(Intersection of results for each condition) / 'or' (union of results for all conditions)


3. **Operator Guide**:
   - Use these operators only: ["contains", "not contains", "start with", "end with", "empty", "not empty", "=", "≠", ">", "<", "≥", "≤", "in", "not in"]
   - Date ranges: Break into two conditions (≥ start_date AND < next_month_start)
   - Negations: Always use "≠" for exclusion terms ("not", "except", "exclude", "≠")
   - Implicit logic: Derive unstated filters (e.g., "July" → [≥ YYYY-07-01, < YYYY-08-01])

4. **Processing Steps**:
   a) Identify ALL filterable attributes in the query (both explicit and implicit)
   b) For dates:
        - Infer missing year from current date if needed
        - Always format dates as "YYYY-MM-DD"
        - Convert ranges: [≥ start, < end]
   c) For values: Match EXACTLY to metadata's value keys
   d) Skip conditions if:
        - Attribute doesn't exist in metadata
        - Value has no match in metadata

5. **Final Output**:
   - ONLY output valid JSON dictionary
   - NO additional text/explanations

**Current Task**:
- Today's date: <<CURRENT_DATE>>
- Available metadata keys: <<METADATA_KEYS>>
- User query: "<<USER_QUESTION>>"
"""

def test_meta_filter(question: str, metadata_structure: dict) -> dict:
    """
    Simulate RagFlow's gen_meta_filter function using OpenRouter API.
    """
    current_date = datetime.datetime.today().strftime('%Y-%m-%d')
    
    # Build prompt using simple string replacement
    prompt = META_FILTER_PROMPT_TEMPLATE.replace(
        "<<CURRENT_DATE>>", current_date
    ).replace(
        "<<METADATA_KEYS>>", json.dumps(metadata_structure, indent=2)
    ).replace(
        "<<USER_QUESTION>>", question
    )
    
    print("="*80)
    print("META FILTER GENERATION TEST")
    print("="*80)
    print(f"\nQuestion: {question}")
    print(f"\nMetadata Structure:")
    print(json.dumps(metadata_structure, indent=2))
    print(f"\nCalling OpenRouter API ({MODEL})...")
    
    # Call OpenRouter API
    response = requests.post(
        OPENROUTER_URL,
        headers={
            "Authorization": f"Bearer {OPENROUTER_API_KEY}",
            "Content-Type": "application/json"
        },
        json={
            "model": MODEL,
            "messages": [
                {"role": "system", "content": prompt},
                {"role": "user", "content": "Generate filters:"}
            ],
            "temperature": 0.1
        },
        timeout=60
    )
    
    if response.status_code != 200:
        print(f"Error: {response.status_code} - {response.text}")
        return {}
    
    result = response.json()
    answer = result['choices'][0]['message']['content']
    
    print(f"\n" + "-"*40)
    print("RAW LLM OUTPUT:")
    print("-"*40)
    print(answer)
    
    # Parse JSON
    import re
    # Remove markdown code blocks if present
    answer = re.sub(r"```json\n?", "", answer)
    answer = re.sub(r"```\n?", "", answer)
    answer = answer.strip()
    
    try:
        filter_result = json.loads(answer)
        print(f"\n" + "-"*40)
        print("PARSED FILTER RESULT:")
        print("-"*40)
        print(json.dumps(filter_result, indent=2, ensure_ascii=False))
        
        # Analyze conditions
        conditions = filter_result.get('conditions', [])
        logic = filter_result.get('logic', 'and')
        
        print(f"\n" + "-"*40)
        print("ANALYSIS:")
        print("-"*40)
        print(f"Logic: {logic}")
        print(f"Number of conditions: {len(conditions)}")
        
        for i, cond in enumerate(conditions):
            print(f"  [{i+1}] {cond['key']} {cond['op']} '{cond['value']}'")
        
        return filter_result
        
    except json.JSONDecodeError as e:
        print(f"\nFailed to parse JSON: {e}")
        return {}


def main():
    # Metadata structure (from actual RagFlow documents)
    metadata_structure = {
        "fund_name": [
            "High Dividend Fund",
            "Classic Fund", 
            "Asian Income Fund"
        ],
        "report_month": [
            "2025-09-01",
            "2025-08-01",
            "2025-07-01",
            "2025-06-01",
            "2025-05-01",
            "2025-04-01",
            "2025-03-01",
            "2025-02-01",
            "2025-01-01"
        ],
        "section_type": [
            "Fund_facts",
            "Fee_structure",
            "Portfolio_characteristics",
            "Monthly_performance",
            "Top_holdings_-_equities",
            "Dividend_information",
            "NAVs_codes",
            "Performance_update",
            "Investment_objective",
            "Credit_ratings",
            "Asset_type_by_sector",
            "Asset_type_by_geography",
            "Top_holdings_-_fixed_income"
        ]
    }
    
    # Test question
    question = "What are top holdings of Asian Income Fund from January to September 2025"
    
    result = test_meta_filter(question, metadata_structure)
    
    # Summary
    print(f"\n" + "="*80)
    print("SUMMARY")
    print("="*80)
    
    if result:
        conditions = result.get('conditions', [])
        
        # Count conditions by type
        date_conditions = [c for c in conditions if c['key'] == 'report_month']
        fund_conditions = [c for c in conditions if c['key'] == 'fund_name']
        section_conditions = [c for c in conditions if c['key'] == 'section_type']
        
        print(f"Date conditions: {len(date_conditions)}")
        print(f"Fund conditions: {len(fund_conditions)}")
        print(f"Section conditions: {len(section_conditions)}")
        print(f"Total conditions: {len(conditions)}")
        
        # Potential ES clause count estimation
        # Each condition becomes at least one clause in ES
        # With "in" operator, it expands to multiple clauses
        estimated_clauses = 0
        for c in conditions:
            if c['op'] in ['in', 'not in']:
                # "in" with multiple values expands
                values = c['value'].split(', ')
                estimated_clauses += len(values)
            else:
                estimated_clauses += 1
        
        print(f"\nEstimated ES filter clauses: {estimated_clauses}")
        print("\nNote: The 'too_many_nested_clauses' error likely comes from")
        print("the BM25 query_string expansion, not from these filter conditions.")


if __name__ == "__main__":
    main()

